### ISSUE TITLE
Question about Table 5 

### ISSUE THREAD

**Issue by Journey7331** [TerryPei/EfficientVMamba#13]
Thanks for your great work !!
And I wonder where this data `VMamba-T 2.4(param) 0.9(gflops) 72.1(top@1)` comes from?
Did you train VMamba-T on your own `Dim=[48, 96, 192, 384] Stage=[2, 2, 4, 2]` to get this version?

No offense, just curious :) 
Maybe I missed some paragraphs that talks about this.

**Comment by TerryPei** [comment]
@Journey7331 Hi, Table 5 is confusing as the `VMamba-T` represents the model using the original cross scan (without ES2D) combined with the Fusion and InRes block, which differs from the original `VMamba-T`. We will modify it to make it clearer in the revised version. We are very grateful to u for helping us improve our work. 👍

**Comment by TerryPei** [comment]
@Journey7331 Hi, VMamba-T in Table 5 differs from the original paper with the configuration:

```
@register_model
def vssm_nano(*args, drop_path_rate=0.1, **kwargs):
    return VSSM(dims=[32, 64, 128, 256], depths=[2, 2, 4, 2], d_state=16, mlp_ratio=0, downsampling='v1', drop_path_rate=drop_path_rate)
```

This model is used to explore whether reducing the FLOPs of VMamba to a level similar to EfficientVMamba can achieve comparable effects. In the caption of Table 5, we state, 'For comparison with the baseline VMamba, we adjust the dimensions and number of layers to match the FLOPs.' The VMamba-T mentioned here may be confused with the model in the original paper, and we will revise this in the later version. We greatly appreciate your pointing this out and helping improve our work. Feel free to ask if u have any other questions.

**Comment by Journey7331** [comment]
Got it, Thanks for your quick reply :)
