### ISSUE TITLE
InvertedResidual

### ISSUE THREAD

**Issue by Kiet0712** [TerryPei/EfficientVMamba#2]
Hi! Thank you for release the code!
I found that in vmamba_efficient.py you have import ''from lib.models.operations import InvertedResidual'' but i cannot find where is the file operations place in the code. Did i miss something ?

**Comment by TerryPei** [comment]
> Hi! Thank you for release the code! I found that in vmamba_efficient.py you have import ''from lib.models.operations import InvertedResidual'' but i cannot find where is the file operations place in the code. Did i miss something ?

Thank you for your helpful question! The code has been updated.  If you encounter any problems later, do not hesitate to contact me.
